name: sm_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  pretty_dio_logger: ^1.4.0
  dio: ^5.7.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_map: ^7.0.2
  location: ^7.0.1
  flutter_spinkit: ^5.2.1
  maplibre_gl: ^0.20.0
  connectivity_plus: ^6.0.5



dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
